name: Checkstyle

on: [push, pull_request]

jobs:
  checkstyle-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Install package
        run: mvn install -U
      - name: Checkstyle check
        run: mvn checkstyle:check
